import type { CountryData } from './types'

/**
 * Real-world minimum wage and cost-of-living dataset.
 *
 * ⚠ STALENESS NOTICE ⚠
 * This data is a static snapshot and may be outdated. Minimum wage rates,
 * exchange rates, and cost-of-living indexes change over time. Verify
 * current figures against official sources before making decisions.
 *
 * Sources (publicly verifiable):
 *  - ILOSTAT / OECD Stat minimum wage databases
 *  - Numbeo Cost of Living Index (NYC = 100 baseline)
 *  - National labour ministries & official gazettes
 *  - World Bank exchange rates (approximate mid-2024 values)
 *
 * Figures are rounded for readability. All commodity prices are in the local
 * currency of the city. When a region has no distinct minimum wage, the
 * national rate is used and the city's cost-of-living indexes still reflect
 * local price levels.
 */
export const COUNTRIES: CountryData[] = [
  {
    id: 'us',
    name: 'United States',
    iso2: 'us',
    currency: 'USD',
    currencySymbol: '$',
    hourlyWageLocal: 7.25,
    standardWorkweekHours: 40,
    usdRate: 1,
    authority: 'Federal (Fair Labor Standards Act); state laws may be higher',
    effectiveDate: '2009-07-24',
    source: 'U.S. Department of Labor',
    cities: [
      {
        id: 'us-nyc',
        name: 'New York City',
        hourlyWageLocal: 16.5,
        costOfLivingIndex: 100,
        rentIndex: 100,
        groceriesIndex: 100,
        restaurantIndex: 100,
        purchasingPowerIndex: 100,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 3.5, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.4, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 4.2, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 5.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 14, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Gasoline', category: 'Transport', priceLocal: 1.05, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.25, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 65, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 132, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 25, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2860,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1900, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 450, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 132, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 180, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 198, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 5720,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 3500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 1100, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 280, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 320, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 520, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'NYC Department of Consumer Affairs; Numbeo',
        year: 2024,
      },
      {
        id: 'us-la',
        name: 'Los Angeles',
        hourlyWageLocal: 16.9,
        costOfLivingIndex: 78,
        rentIndex: 70,
        groceriesIndex: 86,
        restaurantIndex: 85,
        purchasingPowerIndex: 108,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 3.2, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.2, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 3.8, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 5.0, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 12, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Gasoline', category: 'Transport', priceLocal: 1.15, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.32, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 60, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 100, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 20, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2929,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 400, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 100, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 200, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 229, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 5858,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 2800, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 950, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 240, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 350, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 518, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'City of Los Angeles; Numbeo',
        year: 2024,
      },
      {
        id: 'us-chicago',
        name: 'Chicago',
        hourlyWageLocal: 15.8,
        costOfLivingIndex: 70,
        rentIndex: 55,
        groceriesIndex: 80,
        restaurantIndex: 78,
        purchasingPowerIndex: 115,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 2.8, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.0, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 3.2, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 4.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 10, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Gasoline', category: 'Transport', priceLocal: 1.05, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.21, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 55, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 105, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 18, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2738,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1200, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 380, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 105, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 180, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 173, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'City of Chicago; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'gb',
    name: 'United Kingdom',
    iso2: 'gb',
    currency: 'GBP',
    currencySymbol: '£',
    hourlyWageLocal: 11.44,
    standardWorkweekHours: 40,
    usdRate: 1.27,
    authority: 'Low Pay Commission (national living wage for 21+)',
    effectiveDate: '2024-04-01',
    source: 'GOV.UK / Low Pay Commission',
    cities: [
      {
        id: 'gb-london',
        name: 'London',
        hourlyWageLocal: 13.85,
        costOfLivingIndex: 79,
        rentIndex: 75,
        groceriesIndex: 64,
        restaurantIndex: 79,
        purchasingPowerIndex: 86,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 1.4, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.2, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 3.2, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 2.6, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 7.5, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.45, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.34, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 35, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 200, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 18, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2400,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1450, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 320, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 200, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 200, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 230, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 4800,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 2600, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 800, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 400, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 350, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 650, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'London Living Wage Foundation; ONS',
        year: 2024,
      },
      {
        id: 'gb-manchester',
        name: 'Manchester',
        hourlyWageLocal: 11.44,
        costOfLivingIndex: 56,
        rentIndex: 38,
        groceriesIndex: 56,
        restaurantIndex: 60,
        purchasingPowerIndex: 95,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 1.1, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.0, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 2.8, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 2.0, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 6.0, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.4, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.3, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 30, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 90, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 14, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 1983,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 750, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 280, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 90, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 180, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 183, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'ONS; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'de',
    name: 'Germany',
    iso2: 'de',
    currency: 'EUR',
    currencySymbol: '€',
    hourlyWageLocal: 12.41,
    standardWorkweekHours: 40,
    usdRate: 1.08,
    authority: 'Federal Ministry of Labour and Social Affairs',
    effectiveDate: '2024-01-01',
    source: 'Bundesministerium für Arbeit und Soziales',
    cities: [
      {
        id: 'de-berlin',
        name: 'Berlin',
        hourlyWageLocal: 12.82,
        costOfLivingIndex: 64,
        rentIndex: 47,
        groceriesIndex: 56,
        restaurantIndex: 60,
        purchasingPowerIndex: 95,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 1.8, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.0, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 2.6, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 2.2, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 8.5, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.7, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.38, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 35, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 91, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 12, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2222,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 950, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 280, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 91, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 230, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 211, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 4444,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 1700, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 700, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 200, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 380, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 464, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Destatis; Numbeo',
        year: 2024,
      },
      {
        id: 'de-munich',
        name: 'Munich',
        hourlyWageLocal: 12.82,
        costOfLivingIndex: 75,
        rentIndex: 65,
        groceriesIndex: 62,
        restaurantIndex: 70,
        purchasingPowerIndex: 95,
        commodities: [
          { id: 'bread', label: 'Bread (500g)', category: 'Food', priceLocal: 2.0, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.1, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 2.9, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 2.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 9.5, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.75, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.4, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 38, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 63, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 15, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2222,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1300, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 300, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 63, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 240, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 319, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Destatis; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'fr',
    name: 'France',
    iso2: 'fr',
    currency: 'EUR',
    currencySymbol: '€',
    hourlyWageLocal: 11.65,
    standardWorkweekHours: 35,
    usdRate: 1.08,
    authority: 'Ministère du Travail (SMIC)',
    effectiveDate: '2024-11-01',
    source: 'Service-public.fr',
    cities: [
      {
        id: 'fr-paris',
        name: 'Paris',
        hourlyWageLocal: 11.65,
        costOfLivingIndex: 76,
        rentIndex: 65,
        groceriesIndex: 70,
        restaurantIndex: 78,
        purchasingPowerIndex: 84,
        commodities: [
          { id: 'bread', label: 'Baguette', category: 'Food', priceLocal: 1.3, unit: '1', icon: '🥖' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1.2, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 3.4, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 2.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 9.5, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.85, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.25, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 30, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 86, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Bistro Lunch', category: 'Lifestyle', priceLocal: 16, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 1777,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 950, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 300, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 86, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 170, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 271, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 3554,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 1800, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 750, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 180, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 300, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 524, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'INSEE; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'jp',
    name: 'Japan',
    iso2: 'jp',
    currency: 'JPY',
    currencySymbol: '¥',
    hourlyWageLocal: 1055,
    standardWorkweekHours: 40,
    usdRate: 0.0064,
    authority: 'Ministry of Health, Labour and Welfare (prefecture-weighted)',
    effectiveDate: '2024-10-01',
    source: '厚生労働省 (MHLW)',
    cities: [
      {
        id: 'jp-tokyo',
        name: 'Tokyo',
        hourlyWageLocal: 1163,
        costOfLivingIndex: 65,
        rentIndex: 50,
        groceriesIndex: 70,
        restaurantIndex: 50,
        purchasingPowerIndex: 107,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 220, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 220, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 320, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 600, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 800, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Gasoline', category: 'Transport', priceLocal: 180, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 31, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 4500, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 10000, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Conveyor Sushi', category: 'Lifestyle', priceLocal: 1000, unit: '1 meal', icon: '🍣' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 200000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 90000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 45000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 10000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 15000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 40000, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Tokyo Metropolitan Government; Numbeo',
        year: 2024,
      },
      {
        id: 'jp-osaka',
        name: 'Osaka',
        hourlyWageLocal: 1064,
        costOfLivingIndex: 55,
        rentIndex: 35,
        groceriesIndex: 62,
        restaurantIndex: 45,
        purchasingPowerIndex: 110,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 200, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 210, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 300, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 580, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 750, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Gasoline', category: 'Transport', priceLocal: 175, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 29, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 4200, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 8000, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 800, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 184000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 60000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 40000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 8000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 13000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 33000, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Osaka Prefecture; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'pk',
    name: 'Pakistan',
    iso2: 'pk',
    currency: 'PKR',
    currencySymbol: '₨',
    monthlyWageLocal: 32000,
    standardWorkweekHours: 48,
    usdRate: 278,
    authority: 'Provincial Governments (Sindh, Punjab, KP, Balochistan)',
    effectiveDate: '2024-07-01',
    source: 'Provincial Labour Departments',
    cities: [
      {
        id: 'pk-khi',
        name: 'Karachi',
        monthlyWageLocal: 37000,
        costOfLivingIndex: 18,
        rentIndex: 6,
        groceriesIndex: 18,
        restaurantIndex: 12,
        purchasingPowerIndex: 28,
        commodities: [
          { id: 'bread', label: 'Roti Bread', category: 'Food', priceLocal: 30, unit: '1 piece', icon: '🫓' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 220, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 360, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Basmati Rice', category: 'Food', priceLocal: 450, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 600, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 280, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 55, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 4500, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Bus Pass', category: 'Transport', priceLocal: 3500, unit: '1 month', icon: '🚌' },
          { id: 'meal', label: 'Street Dhaba Meal', category: 'Lifestyle', priceLocal: 250, unit: '1 meal', icon: '🍛' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 37000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 12000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 12000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 3500, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 6000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 3500, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 74000,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 25000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 28000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 6000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 9000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 6000, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Sindh Labour Department; PBS',
        year: 2024,
      },
      {
        id: 'pk-lhe',
        name: 'Lahore',
        monthlyWageLocal: 37000,
        costOfLivingIndex: 16,
        rentIndex: 5,
        groceriesIndex: 17,
        restaurantIndex: 11,
        purchasingPowerIndex: 30,
        commodities: [
          { id: 'bread', label: 'Roti Bread', category: 'Food', priceLocal: 25, unit: '1 piece', icon: '🫓' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 200, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 340, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Basmati Rice', category: 'Food', priceLocal: 430, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 580, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 280, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 52, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 4200, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Bus Pass', category: 'Transport', priceLocal: 3000, unit: '1 month', icon: '🚌' },
          { id: 'meal', label: 'Street Dhaba Meal', category: 'Lifestyle', priceLocal: 220, unit: '1 meal', icon: '🍛' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 37000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 10000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 11000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 3000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 5500, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 2500, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Punjab Labour Department; PBS',
        year: 2024,
      },
    ],
  },
  {
    id: 'in',
    name: 'India',
    iso2: 'in',
    currency: 'INR',
    currencySymbol: '₹',
    dailyWageLocal: 269,
    standardWorkweekHours: 48,
    usdRate: 83.5,
    authority: 'Central & State Governments (National Floor Level)',
    effectiveDate: '2024-10-01',
    source: 'Ministry of Labour & Employment',
    cities: [
      {
        id: 'in-mum',
        name: 'Mumbai',
        dailyWageLocal: 410,
        costOfLivingIndex: 27,
        rentIndex: 18,
        groceriesIndex: 26,
        restaurantIndex: 22,
        purchasingPowerIndex: 38,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 45, unit: '400 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 60, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 84, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 70, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 240, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 105, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 8, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 700, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Train Pass', category: 'Transport', priceLocal: 800, unit: '1 month', icon: '🚆' },
          { id: 'meal', label: 'Thali Meal', category: 'Lifestyle', priceLocal: 120, unit: '1 meal', icon: '🍛' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 10700,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 4500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 3500, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 800, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 1000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 900, color: 'var(--chart-5)' },
            ],
          },
          {
            type: 'Family of 4',
            monthlyIncomeLocal: 21400,
            expenses: [
              { category: 'Rent (3-br)', amountLocal: 12000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 6500, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 1500, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 1800, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -400, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Maharashtra Labour Dept; Numbeo',
        year: 2024,
      },
      {
        id: 'in-blr',
        name: 'Bengaluru',
        dailyWageLocal: 410,
        costOfLivingIndex: 24,
        rentIndex: 13,
        groceriesIndex: 25,
        restaurantIndex: 20,
        purchasingPowerIndex: 42,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 45, unit: '400 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 55, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 78, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 65, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 220, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 102, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 7, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 800, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Metro Pass', category: 'Transport', priceLocal: 1200, unit: '1 month', icon: '🚆' },
          { id: 'meal', label: 'Thali Meal', category: 'Lifestyle', priceLocal: 100, unit: '1 meal', icon: '🍛' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 10700,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 5000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 3000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 1200, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 1000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 500, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Karnataka Labour Dept; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'cn',
    name: 'China',
    iso2: 'cn',
    currency: 'CNY',
    currencySymbol: '¥',
    monthlyWageLocal: 2480,
    standardWorkweekHours: 40,
    usdRate: 7.25,
    authority: 'Provincial Human Resources Departments (tiered)',
    effectiveDate: '2024-04-01',
    source: '各省人力资源社会保障厅',
    cities: [
      {
        id: 'cn-sha',
        name: 'Shanghai',
        monthlyWageLocal: 2690,
        costOfLivingIndex: 47,
        rentIndex: 35,
        groceriesIndex: 45,
        restaurantIndex: 35,
        purchasingPowerIndex: 67,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 15, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 14, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 14, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 8, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 28, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 8.3, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.6, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 120, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Metro Pass', category: 'Transport', priceLocal: 200, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 30, unit: '1 meal', icon: '🥡' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2690,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 900, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 200, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 200, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -110, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Shanghai HR & SS Bureau; Numbeo',
        year: 2024,
      },
      {
        id: 'cn-bjs',
        name: 'Beijing',
        monthlyWageLocal: 2420,
        costOfLivingIndex: 46,
        rentIndex: 33,
        groceriesIndex: 44,
        restaurantIndex: 35,
        purchasingPowerIndex: 65,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 14, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 13, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 13, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 7.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 27, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 8.4, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.55, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 110, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Metro Pass', category: 'Transport', priceLocal: 180, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 28, unit: '1 meal', icon: '🥡' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2420,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1400, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 850, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 180, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 200, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -210, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Beijing HR & SS Bureau; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'br',
    name: 'Brazil',
    iso2: 'br',
    currency: 'BRL',
    currencySymbol: 'R$',
    monthlyWageLocal: 1412,
    standardWorkweekHours: 44,
    usdRate: 5.05,
    authority: 'Federal Government (salário mínimo)',
    effectiveDate: '2024-01-01',
    source: 'Ministério do Trabalho',
    cities: [
      {
        id: 'br-sao',
        name: 'São Paulo',
        monthlyWageLocal: 1620,
        costOfLivingIndex: 32,
        rentIndex: 18,
        groceriesIndex: 28,
        restaurantIndex: 30,
        purchasingPowerIndex: 45,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 9, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 6, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 14, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 7, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 18, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 6.5, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.85, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 90, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 260, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Comida a Quilo', category: 'Lifestyle', priceLocal: 28, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 1620,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 800, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 450, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 260, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 180, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -70, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Prefeitura de São Paulo; IBGE',
        year: 2024,
      },
      {
        id: 'br-rio',
        name: 'Rio de Janeiro',
        monthlyWageLocal: 1412,
        costOfLivingIndex: 30,
        rentIndex: 16,
        groceriesIndex: 27,
        restaurantIndex: 28,
        purchasingPowerIndex: 45,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 8, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 5.5, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 13, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 6.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 17, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 6.4, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.9, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 85, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 240, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Prato Feito', category: 'Lifestyle', priceLocal: 22, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 1412,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 700, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 420, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 240, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 180, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -128, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Prefeitura do Rio; IBGE',
        year: 2024,
      },
    ],
  },
  {
    id: 'au',
    name: 'Australia',
    iso2: 'au',
    currency: 'AUD',
    currencySymbol: 'A$',
    hourlyWageLocal: 24.1,
    standardWorkweekHours: 38,
    usdRate: 0.66,
    authority: 'Fair Work Commission',
    effectiveDate: '2024-07-01',
    source: 'Fair Work Commission',
    cities: [
      {
        id: 'au-syd',
        name: 'Sydney',
        hourlyWageLocal: 24.73,
        costOfLivingIndex: 75,
        rentIndex: 70,
        groceriesIndex: 72,
        restaurantIndex: 75,
        purchasingPowerIndex: 102,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 3.5, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 2.2, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 7.5, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 4, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 11, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.95, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.4, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 80, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Opal Pass', category: 'Transport', priceLocal: 217, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 25, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 3750,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 2400, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 500, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 217, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 220, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 413, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Fair Work; Numbeo',
        year: 2024,
      },
      {
        id: 'au-mel',
        name: 'Melbourne',
        hourlyWageLocal: 24.73,
        costOfLivingIndex: 70,
        rentIndex: 60,
        groceriesIndex: 68,
        restaurantIndex: 70,
        purchasingPowerIndex: 108,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 3.2, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 2.0, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 7.0, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 3.8, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 10, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.9, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.38, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 75, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Myki Pass', category: 'Transport', priceLocal: 170, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 22, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 3750,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 2000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 480, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 170, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 210, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 890, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Fair Work; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'ca',
    name: 'Canada',
    iso2: 'ca',
    currency: 'CAD',
    currencySymbol: 'C$',
    hourlyWageLocal: 17.3,
    standardWorkweekHours: 40,
    usdRate: 0.73,
    authority: 'Provincial governments (varies by province)',
    effectiveDate: '2024-10-01',
    source: 'Employment and Social Development Canada',
    cities: [
      {
        id: 'ca-tor',
        name: 'Toronto',
        hourlyWageLocal: 17.2,
        costOfLivingIndex: 72,
        rentIndex: 62,
        groceriesIndex: 68,
        restaurantIndex: 70,
        purchasingPowerIndex: 95,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 3.0, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 2.5, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 4.5, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 14, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.55, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.18, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 70, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'TTC Pass', category: 'Transport', priceLocal: 156, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 22, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2980,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1700, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 450, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 156, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 200, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 474, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Ontario Ministry of Labour; Numbeo',
        year: 2024,
      },
      {
        id: 'ca-van',
        name: 'Vancouver',
        hourlyWageLocal: 17.4,
        costOfLivingIndex: 75,
        rentIndex: 70,
        groceriesIndex: 70,
        restaurantIndex: 72,
        purchasingPowerIndex: 90,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 3.2, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 2.6, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 4.8, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 5.5, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken Breast', category: 'Food', priceLocal: 15, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1.7, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.15, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 75, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'TransLink Pass', category: 'Transport', priceLocal: 185, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 23, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 3014,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 1900, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 470, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 185, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 210, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 249, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'BC Ministry of Labour; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'ae',
    name: 'United Arab Emirates',
    iso2: 'ae',
    currency: 'AED',
    currencySymbol: 'د.إ',
    monthlyWageLocal: 5000,
    standardWorkweekHours: 48,
    usdRate: 0.27,
    authority: 'Ministry of Human Resources (no national minimum; entry-level)',
    effectiveDate: '2023-01-01',
    source: 'MOHRE',
    cities: [
      {
        id: 'ae-dxb',
        name: 'Dubai',
        monthlyWageLocal: 5000,
        costOfLivingIndex: 60,
        rentIndex: 55,
        groceriesIndex: 52,
        restaurantIndex: 50,
        purchasingPowerIndex: 110,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 5, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 6, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 12, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 7, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 18, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol (Special 95)', category: 'Transport', priceLocal: 2.95, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.45, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 350, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Nol Pass', category: 'Transport', priceLocal: 350, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Shawarma Combo', category: 'Lifestyle', priceLocal: 30, unit: '1 meal', icon: '🌯' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 5000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 2500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 1200, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 350, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 500, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 450, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Dubai Statistics Centre; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'za',
    name: 'South Africa',
    iso2: 'za',
    currency: 'ZAR',
    currencySymbol: 'R',
    hourlyWageLocal: 27.58,
    standardWorkweekHours: 45,
    usdRate: 18.5,
    authority: 'Department of Employment and Labour (National Minimum Wage Act)',
    effectiveDate: '2024-03-01',
    source: 'Department of Employment and Labour',
    cities: [
      {
        id: 'za-jnb',
        name: 'Johannesburg',
        hourlyWageLocal: 27.58,
        costOfLivingIndex: 30,
        rentIndex: 16,
        groceriesIndex: 28,
        restaurantIndex: 28,
        purchasingPowerIndex: 60,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 16, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 22, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 50, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 30, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 75, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol (93)', category: 'Transport', priceLocal: 24, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 3.2, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 600, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 800, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 120, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 4976,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 2500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 1500, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 800, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 700, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -524, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Stats SA; Numbeo',
        year: 2024,
      },
      {
        id: 'za-cpt',
        name: 'Cape Town',
        hourlyWageLocal: 27.58,
        costOfLivingIndex: 32,
        rentIndex: 18,
        groceriesIndex: 30,
        restaurantIndex: 30,
        purchasingPowerIndex: 58,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 17, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 24, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 55, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 32, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 80, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 25, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 3.3, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 650, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Public Transport', category: 'Transport', priceLocal: 850, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Inexpensive Meal', category: 'Lifestyle', priceLocal: 130, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 4976,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 2800, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 1600, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 850, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 750, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -1024, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'Stats SA; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'mx',
    name: 'Mexico',
    iso2: 'mx',
    currency: 'MXN',
    currencySymbol: 'Mex$',
    dailyWageLocal: 248.93,
    standardWorkweekHours: 48,
    usdRate: 18.5,
    authority: 'CONASAMI (federal minimum, zone-free since 2022)',
    effectiveDate: '2024-01-01',
    source: 'CONASAMI',
    cities: [
      {
        id: 'mx-mex',
        name: 'Mexico City',
        dailyWageLocal: 248.93,
        costOfLivingIndex: 33,
        rentIndex: 22,
        groceriesIndex: 32,
        restaurantIndex: 30,
        purchasingPowerIndex: 45,
        commodities: [
          { id: 'bread', label: 'Bolillo', category: 'Food', priceLocal: 4, unit: '1 piece', icon: '🥖' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 25, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 60, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 35, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 95, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Magna Petrol', category: 'Transport', priceLocal: 24, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 2.5, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 400, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Metro CDMX', category: 'Transport', priceLocal: 200, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Taquería Combo', category: 'Lifestyle', priceLocal: 80, unit: '1 meal', icon: '🌮' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 7468,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 3500, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 2400, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 200, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 700, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 668, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'INEGI; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'sg',
    name: 'Singapore',
    iso2: 'sg',
    currency: 'SGD',
    currencySymbol: 'S$',
    monthlyWageLocal: 1600,
    standardWorkweekHours: 44,
    usdRate: 0.74,
    authority: 'Progressive Wage Model (sectoral, no national minimum)',
    effectiveDate: '2024-07-01',
    source: 'MOM Singapore',
    cities: [
      {
        id: 'sg-sin',
        name: 'Singapore',
        monthlyWageLocal: 1600,
        costOfLivingIndex: 81,
        rentIndex: 75,
        groceriesIndex: 80,
        restaurantIndex: 50,
        purchasingPowerIndex: 95,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 3.2, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 3.5, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 4.5, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 4, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 9, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol (95)', category: 'Transport', priceLocal: 2.9, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 0.33, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (1 Gbps)', category: 'Utility', priceLocal: 50, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'MRT Pass', category: 'Transport', priceLocal: 120, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Hawker Meal', category: 'Lifestyle', priceLocal: 6, unit: '1 meal', icon: '🍲' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 1600,
            expenses: [
              { category: 'Rent (room)', amountLocal: 800, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 450, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 120, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 120, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 110, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'SingStat; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'kr',
    name: 'South Korea',
    iso2: 'kr',
    currency: 'KRW',
    currencySymbol: '₩',
    hourlyWageLocal: 9860,
    standardWorkweekHours: 40,
    usdRate: 0.00073,
    authority: 'Ministry of Employment and Labor',
    effectiveDate: '2024-01-01',
    source: '고용노동부 (MOEL)',
    cities: [
      {
        id: 'kr-sel',
        name: 'Seoul',
        hourlyWageLocal: 9860,
        costOfLivingIndex: 67,
        rentIndex: 45,
        groceriesIndex: 70,
        restaurantIndex: 50,
        purchasingPowerIndex: 90,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 3500, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 2800, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 4500, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 4500, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 9000, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol', category: 'Transport', priceLocal: 1700, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 180, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 30000, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'T-Money Pass', category: 'Transport', priceLocal: 65000, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Gimbap Meal', category: 'Lifestyle', priceLocal: 8000, unit: '1 meal', icon: '🍱' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 2060000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 800000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 500000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 65000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 120000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: 575000, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'KOSIS; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'ng',
    name: 'Nigeria',
    iso2: 'ng',
    currency: 'NGN',
    currencySymbol: '₦',
    monthlyWageLocal: 70000,
    standardWorkweekHours: 40,
    usdRate: 1600,
    authority: 'Federal Ministry of Labour and Employment',
    effectiveDate: '2024-07-01',
    source: 'Federal Ministry of Labour',
    cities: [
      {
        id: 'ng-lag',
        name: 'Lagos',
        monthlyWageLocal: 70000,
        costOfLivingIndex: 13,
        rentIndex: 8,
        groceriesIndex: 14,
        restaurantIndex: 11,
        purchasingPowerIndex: 15,
        commodities: [
          { id: 'bread', label: 'Bread', category: 'Food', priceLocal: 1200, unit: '500 g', icon: '🍞' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1500, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 3500, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 4000, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 6000, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Petrol (PMS)', category: 'Transport', priceLocal: 1100, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 70, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 25000, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'Bus Pass', category: 'Transport', priceLocal: 18000, unit: '1 month', icon: '🚐' },
          { id: 'meal', label: 'Bukka Meal', category: 'Lifestyle', priceLocal: 1500, unit: '1 meal', icon: '🍛' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 70000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 30000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 25000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 18000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 10000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -13000, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'NBS; Numbeo',
        year: 2024,
      },
    ],
  },
  {
    id: 'ar',
    name: 'Argentina',
    iso2: 'ar',
    currency: 'ARS',
    currencySymbol: 'AR$',
    monthlyWageLocal: 268000,
    standardWorkweekHours: 48,
    usdRate: 950,
    authority: 'Consejo Nacional del Empleo, la Productividad y el Salario',
    effectiveDate: '2024-10-01',
    source: 'Ministerio de Trabajo',
    cities: [
      {
        id: 'ar-bue',
        name: 'Buenos Aires',
        monthlyWageLocal: 268000,
        costOfLivingIndex: 22,
        rentIndex: 12,
        groceriesIndex: 24,
        restaurantIndex: 25,
        purchasingPowerIndex: 35,
        commodities: [
          { id: 'bread', label: 'Pan Francés', category: 'Food', priceLocal: 2500, unit: '500 g', icon: '🥖' },
          { id: 'milk', label: 'Milk', category: 'Food', priceLocal: 1800, unit: '1 L', icon: '🥛' },
          { id: 'eggs', label: 'Eggs', category: 'Food', priceLocal: 4500, unit: '12', icon: '🥚' },
          { id: 'rice', label: 'Rice', category: 'Food', priceLocal: 2500, unit: '1 kg', icon: '🍚' },
          { id: 'chicken', label: 'Chicken', category: 'Food', priceLocal: 5000, unit: '1 kg', icon: '🍗' },
          { id: 'gasoline', label: 'Nafta Súper', category: 'Transport', priceLocal: 1100, unit: '1 L', icon: '⛽' },
          { id: 'electricity', label: 'Electricity', category: 'Utility', priceLocal: 350, unit: '1 kWh', icon: '⚡' },
          { id: 'internet', label: 'Internet (60 Mbps)', category: 'Utility', priceLocal: 30000, unit: '1 month', icon: '🌐' },
          { id: 'transport', label: 'SUBE Pass', category: 'Transport', priceLocal: 25000, unit: '1 month', icon: '🚇' },
          { id: 'meal', label: 'Bodegón Meal', category: 'Lifestyle', priceLocal: 8000, unit: '1 meal', icon: '🍽️' },
        ],
        consumption: [
          {
            type: 'Single',
            monthlyIncomeLocal: 268000,
            expenses: [
              { category: 'Rent (1-br)', amountLocal: 120000, color: 'var(--chart-1)' },
              { category: 'Food', amountLocal: 90000, color: 'var(--chart-2)' },
              { category: 'Transport', amountLocal: 25000, color: 'var(--chart-3)' },
              { category: 'Utilities & Internet', amountLocal: 35000, color: 'var(--chart-4)' },
              { category: 'Other', amountLocal: -2000, color: 'var(--chart-5)' },
            ],
          },
        ],
        source: 'INDEC; Numbeo',
        year: 2024,
      },
    ],
  },
]

/**
 * Convenience indexes for fast lookup.
 * Built once at module load — used by selectors across the app.
 */
export const COUNTRY_INDEX = new Map(COUNTRIES.map((c) => [c.id, c]))

export function getCountry(id: string): CountryData | undefined {
  return COUNTRY_INDEX.get(id)
}

export function getCity(countryId: string, cityId: string) {
  return COUNTRY_INDEX.get(countryId)?.cities.find((c) => c.id === cityId)
}

/** Sorted country list for selector display. */
export const COUNTRIES_SORTED = [...COUNTRIES].sort((a, b) => a.name.localeCompare(b.name))

/** Convert ISO2 to regional indicator emoji for flags. */
export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}
